import { AI_GATEWAY_CONFIG } from "../../config/aiGateway.js";
import type {
  ConfidenceClass,
  GatewayCitation,
  GatewayContext,
  GatewayConfidence,
} from "../../ai/types/index.js";

/**
 * Confidence (spec Step 24 / Section 13).
 *
 * "Confidence must not simply be an arbitrary number generated by the model."
 * Every component below is computed by deterministic application software from
 * system metadata, never from model output. The four components mirror the
 * spec: Evidence Strength + Data Completeness + Pattern Consistency +
 * Model Evaluation = Confidence Classification.
 */

export interface ConfidenceInputs {
  context: GatewayContext;
  citations: GatewayCitation[];
  /** Engine reported a clean stop rather than truncation or a content filter. */
  cleanFinish: boolean;
  /** Generation completed inside the configured budget. */
  withinLatencyBudget: boolean;
  /** Generation produced no warn-level guardrail findings. */
  noWarnings: boolean;
}

function clamp(value: number): number {
  if (!Number.isFinite(value)) return 0;
  return Math.min(Math.max(value, 0), 1);
}

/** Mean evidence quality behind the response, weighted toward actual relevance. */
function evidenceStrength(citations: GatewayCitation[]): number {
  if (citations.length === 0) return 0;

  const scores = citations.map((citation) => {
    const authority = citation.authorityLevel / 5;
    const consensus = citation.consensusLevel / 5;
    const recency = clamp(citation.recencyScore);
    const relevance = clamp(citation.relevanceScore);
    return relevance * 0.4 + authority * 0.25 + consensus * 0.2 + recency * 0.15;
  });

  const mean = scores.reduce((total, score) => total + score, 0) / scores.length;
  // Multiple independent sources are stronger than one.
  const corroborationBonus = Math.min((citations.length - 1) * 0.08, 0.16);
  return clamp(mean + corroborationBonus);
}

/** Share of the signals the deterministic engine was configured to produce. */
function dataCompleteness(context: GatewayContext): number {
  const policySignals = context.deterministic.missingFields;
  const supplied = context.deterministic.suppliedFields;

  if (supplied.length === 0) return 0;

  const expectedCount = supplied.length + policySignals.length;
  if (expectedCount === 0) return 1;

  return clamp(supplied.length / expectedCount);
}

/** Do independent deterministic signals agree with each other? */
function patternConsistency(context: GatewayContext): number {
  const consistent = context.deterministic.consistentSignals.length;
  const conflicting = context.deterministic.conflictingSignals.length;
  const total = consistent + conflicting;

  if (total === 0) return 0.5;

  return clamp(consistent / total);
}

/** Deterministic assessment of the generation event itself. */
function modelEvaluation(inputs: ConfidenceInputs): number {
  let score = 1;

  if (!inputs.cleanFinish) score -= 0.3;
  if (!inputs.withinLatencyBudget) score -= 0.1;
  if (!inputs.noWarnings) score -= 0.2;

  return clamp(score);
}

function classify(score: number): ConfidenceClass {
  const { high, moderate } = AI_GATEWAY_CONFIG.confidence.thresholds;
  if (score >= high) return "high";
  if (score >= moderate) return "moderate";
  return "limited";
}

function buildRationale(
  components: GatewayConfidence["components"],
  confidenceClass: ConfidenceClass
): string[] {
  const rationale: string[] = [];

  if (components.evidenceStrength < 0.35) {
    rationale.push("Approved evidence supporting this response is limited.");
  }
  if (components.dataCompleteness < 0.6) {
    rationale.push("Some expected tracking signals were not supplied, so interpretation is narrower.");
  }
  if (components.patternConsistency < 0.6) {
    rationale.push("Some reported signals point in different directions and were treated cautiously.");
  }
  if (confidenceClass === "limited") {
    rationale.push("Treat these observations as general wellness education, not a personal clinical picture.");
  }
  if (components.evidenceStrength >= 0.6 && components.dataCompleteness >= 0.8) {
    rationale.push("Observations are grounded in approved evidence and a well-populated tracking history.");
  }

  return rationale;
}

export function calculateConfidence(inputs: ConfidenceInputs): GatewayConfidence {
  const components = {
    evidenceStrength: evidenceStrength(inputs.citations),
    dataCompleteness: dataCompleteness(inputs.context),
    patternConsistency: patternConsistency(inputs.context),
    modelEvaluation: modelEvaluation(inputs),
  };

  const weights = AI_GATEWAY_CONFIG.confidence.weights;
  const score = clamp(
    components.evidenceStrength * weights.evidenceStrength +
      components.dataCompleteness * weights.dataCompleteness +
      components.patternConsistency * weights.patternConsistency +
      components.modelEvaluation * weights.modelEvaluation
  );

  const confidenceClass = classify(score);

  return {
    confidenceClass,
    confidenceScore: Number(score.toFixed(4)),
    components: {
      evidenceStrength: Number(components.evidenceStrength.toFixed(4)),
      dataCompleteness: Number(components.dataCompleteness.toFixed(4)),
      patternConsistency: Number(components.patternConsistency.toFixed(4)),
      modelEvaluation: Number(components.modelEvaluation.toFixed(4)),
    },
    rationale: buildRationale(components, confidenceClass),
  };
}
