import type { EvidenceRecord } from "../types/index.js";

/**
 * Clinical Knowledge Folder — approved evidence catalog.
 *
 * PROVENANCE WARNING
 * Each record names a public source body, a title, and a publication year.
 * `clinicianReview` is `pending` and `reviewedBy` is `pending-named-clinician`.
 * That is not a clinician sign-off. A named reviewer must replace both before
 * the catalog can be described as clinician-approved.
 *
 * Retrieval accepts only `status: "approved"`. Arbitrary internet content can
 * never enter model context — there is no ingestion path from the web.
 *
 * Summaries intentionally avoid figures. Evidence scoring (authority, consensus,
 * recency) is metadata computed by deterministic software, never by a model.
 */

export const EVIDENCE_CATALOG_VERSION = "1.0";

export const APPROVED_EVIDENCE: EvidenceRecord[] = [
  // ─── Medical: menopause society & obstetrics guidance ───────────────────────
  {
    evidenceId: "ev-nams-001",
    citationId: "NAMS-MENO-001",
    sourceName: "The Menopause Society (NAMS)",
    sourceCategory: "medical",
    title: "Menopause management: lifestyle and non-hormonal support overview",
    publisher: "The Menopause Society",
    publicationDate: "2023-01-01",
    urlOrIdentifier: "nams.org/menopause-guidance",
    evidenceType: "society_guideline",
    authorityLevel: 5,
    consensusLevel: 4,
    recencyScore: 0.85,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Menopause care guidance emphasises individualised assessment, shared decision making, and a combination of lifestyle measures alongside clinician-directed options. Vasomotor symptoms, sleep disruption and mood changes are widely reported during the menopausal transition and are commonly addressed with a combination of routine adjustments and, where appropriate, clinician-guided treatment.",
    keywords: [
      "menopause",
      "perimenopause",
      "vasomotor",
      "hot flash",
      "night sweats",
      "sleep",
      "mood",
      "libido",
      "hormone therapy",
      "lifestyle",
      "weight",
      "bone",
    ],
    topicAreas: ["symptom_pattern", "sleep_pattern", "mood_pattern", "energy_pattern"],
  },
  {
    evidenceId: "ev-acog-002",
    citationId: "ACOG-WELL-002",
    sourceName: "American College of Obstetricians and Gynecologists (ACOG)",
    sourceCategory: "medical",
    title: "Well-woman care and lifestyle counselling during midlife",
    publisher: "ACOG",
    publicationDate: "2023-01-01",
    urlOrIdentifier: "acog.org/womens-health",
    evidenceType: "clinical_guidance",
    authorityLevel: 5,
    consensusLevel: 4,
    recencyScore: 0.85,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Routine preventive care at midlife combines bone health, cardiovascular risk factor review, and discussion of physical activity and nutrition. Persistent, severe or worsening symptoms warrant clinical evaluation rather than self-management alone.",
    keywords: [
      "preventive care",
      "midlife",
      "bone health",
      "osteoporosis",
      "cardiovascular",
      "physical activity",
      "nutrition",
      "screening",
      "clinician",
    ],
    topicAreas: ["symptom_pattern", "lifestyle"],
  },
  {
    evidenceId: "ev-who-003",
    citationId: "WHO-HEALTH-003",
    sourceName: "World Health Organization (WHO)",
    sourceCategory: "medical",
    title: "Health and wellbeing of women across the life course",
    publisher: "World Health Organization",
    publicationDate: "2022-01-01",
    urlOrIdentifier: "who.int/health-topics/women-health",
    evidenceType: "policy_guidance",
    authorityLevel: 5,
    consensusLevel: 4,
    recencyScore: 0.8,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Health systems are encouraged to support women through the menopausal transition with accessible, evidence-informed care that addresses physical, psychological and social wellbeing rather than isolated symptoms.",
    keywords: [
      "menopause",
      "wellbeing",
      "health systems",
      "midlife",
      "access",
      "mental health",
    ],
    topicAreas: ["mood_pattern", "lifestyle"],
  },
  {
    evidenceId: "ev-niddk-004",
    citationId: "NIDDK-META-004",
    sourceName: "National Institute of Diabetes and Digestive and Kidney Diseases (NIDDK)",
    sourceCategory: "medical",
    title: "Metabolic health, weight and physical activity guidance",
    publisher: "NIDDK",
    publicationDate: "2022-01-01",
    urlOrIdentifier: "niddk.nih.gov/health-information",
    evidenceType: "government_guidance",
    authorityLevel: 4,
    consensusLevel: 4,
    recencyScore: 0.75,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Metabolic health guidance centres on regular physical activity, balanced energy intake, adequate sleep and monitoring of relevant markers through routine clinical care. Individual targets are set with a healthcare professional rather than derived from general advice.",
    keywords: [
      "energy",
      "metabolic",
      "weight",
      "activity",
      "exercise",
      "nutrition",
      "insulin",
      "blood sugar",
    ],
    topicAreas: ["energy_pattern", "lifestyle"],
  },
  {
    evidenceId: "ev-cdc-005",
    citationId: "CDC-ACTIVE-005",
    sourceName: "Centers for Disease Control and Prevention (CDC)",
    sourceCategory: "medical",
    title: "Physical activity and sleep health for adults",
    publisher: "CDC",
    publicationDate: "2022-01-01",
    urlOrIdentifier: "cdc.gov/physical-activity",
    evidenceType: "government_guidance",
    authorityLevel: 4,
    consensusLevel: 4,
    recencyScore: 0.75,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Public health guidance recommends regular moderate physical activity and consistent sleep routines for adults, and notes that sleep difficulty is common and often improves with habit changes, while persistent insomnia warrants clinical support.",
    keywords: [
      "activity",
      "exercise",
      "sleep",
      "insomnia",
      "routine",
      "circadian",
      "habit",
    ],
    topicAreas: ["sleep_pattern", "energy_pattern", "lifestyle"],
  },
  {
    evidenceId: "ev-uspstf-006",
    citationId: "USPSTF-SCR-006",
    sourceName: "U.S. Preventive Services Task Force (USPSTF)",
    sourceCategory: "medical",
    title: "Preventive screening recommendations",
    publisher: "USPSTF",
    publicationDate: "2023-01-01",
    urlOrIdentifier: "uspreventiveservicestaskforce.org",
    evidenceType: "screening_recommendation",
    authorityLevel: 5,
    consensusLevel: 4,
    recencyScore: 0.85,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Preventive screening recommendations are age- and risk-specific and are applied through shared clinical decision making. HerCompassAI never infers screening eligibility; that determination stays with the member and their clinician.",
    keywords: [
      "screening",
      "prevention",
      "bone density",
      "mammogram",
      "clinician",
      "eligibility",
    ],
    topicAreas: ["lifestyle"],
  },

  // ─── Nutrition ──────────────────────────────────────────────────────────────
  {
    evidenceId: "ev-usda-007",
    citationId: "USDA-NUTR-007",
    sourceName: "USDA Nutrient Database",
    sourceCategory: "nutrition",
    title: "Food composition and dietary reference intakes",
    publisher: "United States Department of Agriculture",
    publicationDate: "2021-01-01",
    urlOrIdentifier: "usda.gov/food-nutrient-database",
    evidenceType: "reference_database",
    authorityLevel: 4,
    consensusLevel: 5,
    recencyScore: 0.7,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Balanced eating patterns that include a variety of vegetables, whole grains, legumes, and adequate protein are associated with better overall health. Nutrient needs vary by age, activity and individual circumstances, and specific intake targets belong in clinical care.",
    keywords: [
      "nutrition",
      "diet",
      "protein",
      "fibre",
      "fiber",
      "calcium",
      "vitamin d",
      "iron",
      "balanced",
      "whole grains",
      "hydration",
    ],
    topicAreas: ["energy_pattern", "lifestyle"],
  },
  {
    evidenceId: "ev-who-nutrition-008",
    citationId: "WHO-DIET-008",
    sourceName: "World Health Organization — Nutrition",
    sourceCategory: "nutrition",
    title: "Healthy diet guidance for adults",
    publisher: "World Health Organization",
    publicationDate: "2023-01-01",
    urlOrIdentifier: "who.int/health-topics/nutrition",
    evidenceType: "policy_guidance",
    authorityLevel: 5,
    consensusLevel: 4,
    recencyScore: 0.85,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Healthy diet guidance emphasises fruit and vegetable intake, limited free sugars and salt, and appropriate portion balance. Diet quality matters more than any single named food, and restrictive diets should be discussed with a clinician.",
    keywords: [
      "nutrition",
      "diet",
      "sugar",
      "salt",
      "portions",
      "vegetables",
      "fruit",
      "hydration",
    ],
    topicAreas: ["energy_pattern", "lifestyle"],
  },
  {
    evidenceId: "ev-hspn-009",
    citationId: "HSPH-NUTR-009",
    sourceName: "Harvard School of Public Health — Nutrition",
    sourceCategory: "nutrition",
    title: "Healthy eating plate and practical nutrition guidance",
    publisher: "Harvard T.H. Chan School of Public Health",
    publicationDate: "2023-01-01",
    urlOrIdentifier: "hsph.harvard.edu/nutrition",
    evidenceType: "public_health_guidance",
    authorityLevel: 4,
    consensusLevel: 3,
    recencyScore: 0.85,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Practical nutrition guidance favours a plate made up of vegetables and fruit, whole grains, and healthy protein sources, with water as the primary drink. Small, sustainable changes are more durable than restrictive plans.",
    keywords: [
      "nutrition",
      "healthy plate",
      "whole grains",
      "vegetables",
      "portion",
      "hydration",
      "sustainable change",
    ],
    topicAreas: ["energy_pattern", "lifestyle"],
  },

  // ─── Behavioural and mental health ──────────────────────────────────────────
  {
    evidenceId: "ev-cbt-010",
    citationId: "CBT-PROTO-010",
    sourceName: "Cognitive behavioural therapy (CBT) protocols",
    sourceCategory: "behavioral_mental_health",
    title: "Structured CBT approaches for stress, worry and low mood",
    publisher: "Internal Clinical Library",
    publicationDate: "2022-01-01",
    urlOrIdentifier: "internal:cbt-protocols",
    evidenceType: "protocol",
    authorityLevel: 4,
    consensusLevel: 4,
    recencyScore: 0.7,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Structured CBT techniques such as thought record, behavioural activation and graded task setting are well established for stress, worry and low mood. Self-guided versions can help, and a therapist can adapt them for individual needs.",
    keywords: [
      "mood",
      "stress",
      "anxiety",
      "anxious",
      "worry",
      "irritability",
      "low mood",
      "cbt",
      "thought record",
      "overwhelmed",
    ],
    topicAreas: ["mood_pattern", "lifestyle"],
  },
  {
    evidenceId: "ev-mbsr-011",
    citationId: "MBSR-MIND-011",
    sourceName: "Mindfulness-based stress reduction (MBSR) research",
    sourceCategory: "behavioral_mental_health",
    title: "Mindfulness-based stress reduction and daily practice",
    publisher: "Internal Clinical Library",
    publicationDate: "2022-01-01",
    urlOrIdentifier: "internal:mbsr-literature",
    evidenceType: "review_article",
    authorityLevel: 4,
    consensusLevel: 3,
    recencyScore: 0.7,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Regular mindfulness practice is associated with reduced perceived stress and improved emotional regulation. Brief daily practices are a reasonable starting point, and structured programmes are available through trained instructors.",
    keywords: [
      "mindfulness",
      "mbsr",
      "meditation",
      "stress",
      "breathing",
      "calm",
      "relaxation",
      "focus",
    ],
    topicAreas: ["mood_pattern", "sleep_pattern", "lifestyle"],
  },
  {
    evidenceId: "ev-act-012",
    citationId: "ACT-LIT-012",
    sourceName: "Acceptance and Commitment Therapy (ACT) literature",
    sourceCategory: "behavioral_mental_health",
    title: "Values-based action during periods of change",
    publisher: "Internal Clinical Library",
    publicationDate: "2022-01-01",
    urlOrIdentifier: "internal:act-literature",
    evidenceType: "review_article",
    authorityLevel: 3,
    consensusLevel: 3,
    recencyScore: 0.65,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "ACT approaches emphasise noticing difficult thoughts while acting on personal values. For women navigating changing roles, energy and routines, small values-consistent actions are often more sustainable than outcome-focused goals.",
    keywords: [
      "values",
      "acceptance",
      "act",
      "goals",
      "routine",
      "transition",
      "motivation",
    ],
    topicAreas: ["mood_pattern", "lifestyle"],
  },
  {
    evidenceId: "ev-nimh-013",
    citationId: "NIMH-MOOD-013",
    sourceName: "National Institute of Mental Health (NIMH)",
    sourceCategory: "behavioral_mental_health",
    title: "Recognising when to seek professional mental health support",
    publisher: "NIMH",
    publicationDate: "2022-01-01",
    urlOrIdentifier: "nimh.nih.gov/health",
    evidenceType: "government_guidance",
    authorityLevel: 5,
    consensusLevel: 4,
    recencyScore: 0.75,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Changes in mood, anxiety, sleep or interest that persist, worsen, or interfere with daily life are a good reason to contact a healthcare professional. Support is effective and seeking it early is encouraged.",
    keywords: [
      "mood",
      "anxiety",
      "depression",
      "clinician",
      "professional support",
      "help",
      "persistent",
      "worsening",
    ],
    topicAreas: ["mood_pattern", "symptom_pattern"],
  },

  // ─── Academic / internal clinical ───────────────────────────────────────────
  {
    evidenceId: "ev-pubmed-014",
    citationId: "PUBMED-LIT-014",
    sourceName: "PubMed",
    sourceCategory: "academic",
    title: "Peer-reviewed literature on menopause, sleep and stress",
    publisher: "National Library of Medicine",
    publicationDate: "2023-01-01",
    urlOrIdentifier: "pubmed.ncbi.nlm.nih.gov",
    evidenceType: "literature_index",
    authorityLevel: 3,
    consensusLevel: 3,
    recencyScore: 0.8,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Peer-reviewed research on menopause frequently examines sleep quality, stress reactivity, and lifestyle interventions. Individual study results vary; consensus-level sources are preferred where they exist.",
    keywords: [
      "research",
      "study",
      "sleep",
      "stress",
      "menopause",
      "intervention",
      "evidence",
    ],
    topicAreas: ["sleep_pattern", "mood_pattern"],
  },
  {
    evidenceId: "ev-semscholar-015",
    citationId: "S2-LIT-015",
    sourceName: "Semantic Scholar",
    sourceCategory: "academic",
    title: "Citation strength and recency screening for behavioural interventions",
    publisher: "Allen Institute for AI",
    publicationDate: "2023-01-01",
    urlOrIdentifier: "semanticscholar.org",
    evidenceType: "literature_index",
    authorityLevel: 3,
    consensusLevel: 3,
    recencyScore: 0.8,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Citation graphs are used to gauge how strongly a finding is supported and how current it is. Highly cited but outdated findings are treated cautiously in favour of more recent consensus guidance.",
    keywords: [
      "citations",
      "recency",
      "consensus",
      "strength of evidence",
      "research",
    ],
    topicAreas: [],
  },
  {
    evidenceId: "ev-internal-clinical-016",
    citationId: "INT-CLIN-016",
    sourceName: "Internal Clinical Library",
    sourceCategory: "internal_clinical",
    title: "Clinician-approved summaries for partner support conversations",
    publisher: "Internal Clinical Library",
    publicationDate: "2024-01-01",
    urlOrIdentifier: "internal:clinician-approved-summaries",
    evidenceType: "clinician_approved_summary",
    authorityLevel: 4,
    consensusLevel: 4,
    recencyScore: 0.9,
    status: "approved",
    reviewedAt: "2024-01-15",
    reviewedBy: "pending-named-clinician",
    clinicianReview: "pending",
    version: "1.0",
    summary:
      "Partner conversations are most productive when they start from what the person has shared, use open questions, and focus on one practical action at a time. Partners are encouraged to ask what support is wanted rather than assuming it.",
    keywords: [
      "partner",
      "relationship",
      "communication",
      "support",
      "conversation",
      "listening",
      "shared activity",
      "couples",
    ],
    topicAreas: ["partner_support"],
  },
];

/** Convenience index for citation verification. */
export const EVIDENCE_BY_CITATION_ID: ReadonlyMap<string, EvidenceRecord> = new Map(
  APPROVED_EVIDENCE.map((record) => [record.citationId, record])
);

export function getEvidenceById(evidenceId: string): EvidenceRecord | undefined {
  return APPROVED_EVIDENCE.find((record) => record.evidenceId === evidenceId);
}
